### ISSUE TITLE
Broker InstanceName Problem

### ISSUE THREAD

**Issue by jzmq** [linkedin/pinot#10]
if I set 
```
./pinot-admin.sh StartBroker -brokerPort 8099 -zkAddress "localhost:2181" -brokerInstName "MyNameIsBroker"
```
Then I received Exception below:
```
ZKExceptionHandler - Exception while invoking init callback for listener:com.linkedin.pinot.broker.broker.helix.LiveInstancesChangeListenerImpl@50b7114a
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.linkedin.pinot.broker.broker.helix.LiveInstancesChangeListenerImpl.onLiveInstanceChange(LiveInstancesChangeListenerImpl.java:75)
	at org.apache.helix.manager.zk.CallbackHandler.invoke(CallbackHandler.java:173)
	at org.apache.helix.manager.zk.CallbackHandler.init(CallbackHandler.java:324)
	at org.apache.helix.manager.zk.CallbackHandler.<init>(CallbackHandler.java:114)
	at org.apache.helix.manager.zk.ZKHelixManager.addListener(ZKHelixManager.java:299)
	at org.apache.helix.manager.zk.ZKHelixManager.addLiveInstanceChangeListener(ZKHelixManager.java:318)
	at com.linkedin.pinot.broker.broker.helix.HelixBrokerStarter.<init>(HelixBrokerStarter.java:120)
	at com.linkedin.pinot.tools.admin.command.StartBrokerCommand.execute(StartBrokerCommand.java:98)
	at com.linkedin.pinot.tools.admin.PinotAdministrator.execute(PinotAdministrator.java:85)
	at com.linkedin.pinot.tools.admin.PinotAdministrator.main(PinotAdministrator.java:94)
```
So is this an issue?

**Comment by jfim** [comment]
We assume that the instance names always start with "Broker_" or "Server_" and contain the instance's address and port; we'll come up with a resolution for this.

**Comment by jfim** [comment]
Tracked internally as PINOT-1658.

The workaround is to use a broker instance name of the form "Broker_address_port" and the default should be fine. Can you check if this issue happens if your broker instance name is something like "Broker_127.0.0.1_8099"?

**Comment by jzmq** [comment]
I didn't set broker name that starts with "Broker_" , I just set randomly . I know the reason, thanks
