### ISSUE TITLE
error mvn install package  -DskipTests

### ISSUE THREAD

**Issue by nekulin** [linkedin/pinot#11]
[INFO] Total time: 51.248s
	[INFO] Finished at: Wed Jun 17 13:19:19 EDT 2015
	[INFO] Final Memory: 121M/237M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (make-bundles) on project pinot-distribution: Failed to create assembly: Error creating assembly archive bin: Problem creating zip: Execution exception: Java heap space -> [Help 1]
	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (make-bundles) on project pinot-distribution: Failed to create assembly: Error creating assembly archive bin: Problem creating zip: Execution exception
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)

**Comment by jfim** [comment]
It would seem that Maven runs out of heap space. Can you try setting MAVEN_OPTS to give it more heap space? Running this before doing `mvn -DskipTests install` should work:

```bash
export MAVEN_OPTS="-Xmx1G"
```

**Comment by nekulin** [comment]
It helped, thanks!

**Comment by ethicstechOSS** [comment]
It also works for me. Thanks.

**Comment by smoo12** [comment]
Thank you so much. That is helpful.
