### ISSUE TITLE
Realtime server Mmap failed due to OOM

### ISSUE THREAD

**Issue by fx19880617** [linkedin/pinot#117]
This is my jvm setting:

> /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xms10G -Xmx40G -XX:MaxDirectMemorySize=100g -server -d64 -XX:+DisableExplicitGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/var/log/upinot/logs/gc-pinot-server.log -XX:+UseG1GC 

2016/05/02 14:34:46.089 ERROR [MmapUtils] Failed to mmap file (size 726, context /var/upinot/pinot-server/dataDir/chaperone2Audit_REALTIME/_tmp/tmp-1462199685139/tmp-1462199685143-704408238606069831/tier.dict (/var/upinot/pinot-server/dataDir/chaperone2Audit_REALTIME/_tmp/tmp-1462199685139/tmp-1462199685143-704408238606069831/tier.dictcom.linkedin.pinot.core.io.writer.impl.FixedByteSingleValueMultiColWriter))
java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:940)
        at com.linkedin.pinot.common.utils.MmapUtils.mmapFile(MmapUtils.java:228)
        at com.linkedin.pinot.core.segment.memory.PinotByteBuffer.mapFromFile(PinotByteBuffer.java:98)
        at com.linkedin.pinot.core.segment.memory.PinotDataBuffer.mapFromFile(PinotDataBuffer.java:94)
        at com.linkedin.pinot.core.segment.memory.PinotDataBuffer.fromFile(PinotDataBuffer.java:82)
        at com.linkedin.pinot.core.io.writer.impl.FixedByteSingleValueMultiColWriter.<init>(FixedByteSingleValueMultiColWriter.java:46)
        at com.linkedin.pinot.core.segment.creator.impl.SegmentDictionaryCreator.build(SegmentDictionaryCreator.java:168)
        at com.linkedin.pinot.core.segment.creator.impl.SegmentColumnarIndexCreator.init(SegmentColumnarIndexCreator.java:111)
        at com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl.buildRaw(SegmentIndexCreationDriverImpl.java:299)
        at com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl.build(SegmentIndexCreationDriverImpl.java:133)
        at com.linkedin.pinot.core.realtime.converter.RealtimeSegmentConverter.build(RealtimeSegmentConverter.java:99)
        at com.linkedin.pinot.core.data.manager.realtime.RealtimeSegmentDataManager$2.run(RealtimeSegmentDataManager.java:244)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Map failed
        at sun.nio.ch.FileChannelImpl.map0(Native Method)
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:937)
        ... 12 more

**Comment by jfim** [comment]
This can be caused by running out of mmap or file handles. On Linux, you can change the `vm.max_map_count` sysctl to increase the number of files that can be mmap'ed concurrently and the `fs.file-max` sysctl to increase the number of files that can be open concurrently. This will be alleviated when we merge all columns from a segment into a segment file, which should be coming soon.
