### ISSUE TITLE
java.net.UnknownHostException occurs during quick-start-offline.sh

### ISSUE THREAD

**Issue by IPL** [linkedin/pinot#18]
The reason is that ```PostQueryCommand._brokerHost``` is only initialized in ```execute()``` but not in ```run()```. Please see below trace.

```java
Offline quickstart complete
Total number of documents in the table
Query : select count(*) from baseballStats limit 0
2015/06/26 16:06:20.135 ERROR [org.apache.zookeeper.server.NIOServerCnxn] [] Thread Thread[main,5,main] died
java.net.UnknownHostException: null
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1091)
        at com.linkedin.pinot.tools.admin.command.PostQueryCommand.run(PostQueryCommand.java:92)
        at com.linkedin.pinot.tools.admin.command.QuickstartRunner.runQuery(QuickstartRunner.java:148)
        at com.linkedin.pinot.tools.Quickstart.execute(Quickstart.java:174)
        at com.linkedin.pinot.tools.Quickstart.main(Quickstart.java:218)
```

**Comment by mayankshriv** [comment]
Thanks for pointing this out, this will be fixed asap.

**Comment by mayankshriv** [comment]
The issue has been resolved. Please try and let us know if you still see an issue.
