### ISSUE TITLE
quick-start-offline encountered noclass exception

### ISSUE THREAD

**Issue by feng-tao** [linkedin/pinot#2567]
after I run and install maven command to install all the dependencies, I try to a quick start command:

/playground/pinot/pinot-distribution/target/pinot-0.016-pkg $ bin/quick-start-offline.sh
/Users/tfeng/playground/pinot/pinot-distribution/target/pinot-0.016-pkg/lib
***** Starting Zookeeper, controller, broker and server *****
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/Log
	at com.linkedin.pinot.tools.admin.command.StartControllerCommand.execute(StartControllerCommand.java:138)
	at com.linkedin.pinot.tools.admin.command.QuickstartRunner.startControllers(QuickstartRunner.java:87)
	at com.linkedin.pinot.tools.admin.command.QuickstartRunner.startAll(QuickstartRunner.java:124)
	at com.linkedin.pinot.tools.Quickstart.execute(Quickstart.java:164)
	at com.linkedin.pinot.tools.Quickstart.main(Quickstart.java:227)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.Log
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

The library seems to be there though:
~/playground/pinot/pinot-distribution/target/pinot-0.016-pkg $ ls lib/commons-logging-1.2.jar
lib/commons-logging-1.2.jar

**Comment by esoterick** [comment]
@feng-tao if you updated the quick-start-offline.sh line 80 from commons-logging-1.1.1.jar -> commons-logging-1.2.jar things should just work.
