### ISSUE TITLE
quick-start-offline.sh return to error "URI is not hierarchical"

### ISSUE THREAD

**Issue by hgword** [linkedin/pinot#4]
Dear linkedin

after compile pinot, I try to start pinot 

./quick-start-offline.sh
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:392)
        at com.linkedin.pinot.tools.Quickstart.execute(Quickstart.java:112)
        at com.linkedin.pinot.tools.Quickstart.main(Quickstart.java:201)

but it return error

**Comment by hgword** [comment]
Sorry it's my fault.
I have to locate pinot-0.016-pkg directory.
and ./bin/quick-start-offline.sh
