### ISSUE TITLE
"select *" failed with exception

### ISSUE THREAD

**Issue by izzizz** [linkedin/pinot#51]
Caught exception while reducing results
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.AbstractList.removeRange(AbstractList.java:571)
	at java.util.AbstractList.clear(AbstractList.java:234)
	at com.linkedin.pinot.core.query.selection.SelectionOperatorUtils.getSelectionColumns(SelectionOperatorUtils.java:99)
	at com.linkedin.pinot.core.query.selection.SelectionOperatorUtils.render(SelectionOperatorUtils.java:156)
	at com.linkedin.pinot.core.query.reduce.DefaultReduceService.reduceOnSelectionResults(DefaultReduceService.java:201)
	at com.linkedin.pinot.core.query.reduce.DefaultReduceService.reduceOnDataTable(DefaultReduceService.java:157)
	at com.linkedin.pinot.requestHandler.BrokerRequestHandler$1.call(BrokerRequestHandler.java:305)
	at com.linkedin.pinot.requestHandler.BrokerRequestHandler$1.call(BrokerRequestHandler.java:302)
	at com.linkedin.pinot.common.metrics.AbstractMetrics.timePhase(AbstractMetrics.java:103)
	at com.linkedin.pinot.requestHandler.BrokerRequestHandler.getDataTableFromBrokerRequest(BrokerRequestHandler.java:302)
	at com.linkedin.pinot.requestHandler.BrokerRequestHandler.processSingleTableBrokerRequest(BrokerRequestHandler.java:157)
	at com.linkedin.pinot.requestHandler.BrokerRequestHandler.processBrokerRequest(BrokerRequestHandler.java:123)
	at com.linkedin.pinot.broker.servlet.PinotClientRequestServlet$1.call(PinotClientRequestServlet.java:141)
	at com.linkedin.pinot.broker.servlet.PinotClientRequestServlet$1.call(PinotClientRequestServlet.java:136)
	at com.linkedin.pinot.common.metrics.AbstractMetrics.timePhase(AbstractMetrics.java:103)
	at com.linkedin.pinot.broker.servlet.PinotClientRequestServlet.handleRequest(PinotClientRequestServlet.java:135)
	at com.linkedin.pinot.broker.servlet.PinotClientRequestServlet.doPost(PinotClientRequestServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:365)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kishoreg** [comment]
This is a regression,we will push the fix shortly.

**Comment by kishoreg** [comment]
Its fixed. Please pull the latest
