### ISSUE TITLE
Terminating quickstart with SIGINT throws IllegalStateException because of shutdown hook

### ISSUE THREAD

**Issue by uce** [linkedin/pinot#6]
Terminating `bin/quick-start-offline.sh` with `SIGINT (ctrl+c`) throws the following Exception:

```
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at com.linkedin.pinot.tools.admin.command.AbstractBaseCommand.<init>(AbstractBaseCommand.java:44)
	at com.linkedin.pinot.tools.admin.command.StopProcessCommand.<init>(StopProcessCommand.java:32)
	at com.linkedin.pinot.tools.admin.command.QuickstartRunner.stop(QuickstartRunner.java:109)
	at com.linkedin.pinot.tools.Quickstart$1.run(Quickstart.java:145)
```

The problem is that the `AbstractBaseCommand` always registers the shutdown hook w/o handling the case that the shutdown is already in progress. For `StopProcessCommand` the shutdown is always in progress (modulo slow timings).

I think it's OK to ignore the exception or just call `cleanup` in the constructor if the general contract is that cleanup must be called in any case.

**Comment by dhaval2025** [comment]
thank you @uce for letting us know.. its been fixed.
